import os
import re

path = r'D:\SolarAI_Dashboard\solar_dashboard_v9.html'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# We extract the old DE_TO_EN object and replace it with a comprehensive one.
OLD_DICT_START = "const DE_TO_EN = {"
OLD_DICT_END = "const EN_TO_DE = {};"
start_idx = content.find(OLD_DICT_START)
end_idx = content.find(OLD_DICT_END)

if start_idx == -1 or end_idx == -1:
    print("Cannot find dictionary")
    exit()

NEW_DICT = '''const DE_TO_EN = {
  'Übersicht': 'Overview',
  'Wetter': 'Weather',
  'Thermospeicher': 'Thermal Storage',
  'Sensoren': 'Sensors',
  'Wartungslog': 'Maintenance Log',
  'Markt-News': 'Market News',
  'Energiemanagement · Süddeutschland': 'Energy Management · South Germany',
  'Online': 'Online',
  'System': 'System',
  'Benachrichtigungen': 'Notifications',
  'News (Neu)': 'News (New)',
  'Netzausfall erkannt': 'Power Grid Failure Detected',
  'Vor 2 Minuten': '2 Minutes Ago',
  'Vor 15 Minuten': '15 Minutes Ago',
  'Speicher > 70% geladen': 'Battery > 70% Charged',
  'KRITISCHER SYSTEMALARM': 'CRITICAL SYSTEM ALARM',
  'Akzeptieren & Schließen': 'Accept & Close',
  'Heutige Ausbeute': 'Daily Yield',
  'Netz-Import': 'Grid Import',
  'Batteriespeicher': 'Battery Storage',
  'Heutige Speicherkosten': 'Daily Storage Cost',
  'Verdient durch Einspeisung': 'Earned by Export',
  'Gesamteinsparung': 'Total Savings',
  'Speichernetzwerk & Leistungskurve': 'Storage Network & Power Curve',
  'Aktivität / Prognose': 'Activity / Forecast',
  '24h Historie': '24h History',
  '30 Tage': '30 Days',
  '12 Monate': '12 Months',
  'Aktuelles Wetter': 'Current Weather',
  'Aktuelles Wetter & 7-Tage-Prognose — Regensburg, Bayern': 'Current Weather & 7-Day Forecast — Regensburg, Bavaria',
  'Sonnenaufgang': 'Sunrise',
  'Sonnenuntergang': 'Sunset',
  'Wolkendecke': 'Cloud Cover',
  'Stündliche Prognose': 'Hourly Forecast',
  'Stündliche Prognose — Heute': 'Hourly Forecast — Today',
  'Thermische Schichtung': 'Thermal Stratification',
  'Wechselrichter meldet Übertemperatur (85°C). Sicherheitsabschaltung wurde eingeleitet. Bitte Anlage sofort prüfen!': 'Inverter reports overtemperature (85°C). Safety shutdown initiated. Please check system immediately!',
  'Wartungslog — KI Aktionen': 'Maintenance Log — AI Actions',
  'Letzte Systemanpassungen': 'Recent System Adjustments',
  'Admin Override': 'Admin Override',
  'Manuelle Steuerung': 'Manual Control',
  'KI-Steuerung wiederhergestellt — automatischer Betrieb aktiv': 'AI Control Restored — Automatic mode active',
  'Tag': 'Day',
  'Der Thermospeicher hält mit seiner guten Dämmung (0.3°C/h Verlust) bis morgen Nachmittag problemlos die Zieltemperatur.': 'Thermal battery easily maintains target temperature until tomorrow afternoon due to excellent insulation (0.3°C/h loss).',
  'Dein vollständiger Strombedarf aus dem Netz wäre': 'Your total electricity demand from the grid would be',
  'Heute': 'Today',
  'Morgen': 'Tomorrow',
  'KI: SELL': 'AI: SELL',
  'KI: USE': 'AI: USE',
  'KI: STORE': 'AI: STORE',
  'KI-Entscheidungsprotokoll': 'AI Decision Log',
  'KI-Entscheidungsprotokoll & Systemstatus': 'AI Decision Log & System Status',
  'KI-Zieltemperatur': 'AI Target Temperature',
  'Morgen Nachmittag steigen die Spotpreise voraussichtlich auf': 'Tomorrow afternoon spot prices are expected to rise to',
  'Morgen teilweise bewölkt mit Aufheiterungen am Nachmittag. Erwartete Solarproduktion:': 'Tomorrow partly cloudy with clearings in the afternoon. Expected solar production:',
  'Morgen — Prognose & Handlungsempfehlungen': 'Tomorrow — Forecast & Actionable Recommendations',
  'Preis: €': 'Price: €',
  'Strombedarf aus Storage gedeckt': 'Electricity demand met from Storage',
  'Einspeisung': 'Export',
  'Laden': 'Store',
  'Eigenverbrauch': 'Self-consumption',
  'Verlustrate': 'Loss Rate',
  'Verlustrate:': 'Loss Rate:',
  'Wetterdaten:': 'Weather Data:',
  'Wetter-Hero': 'Weather-Hero',
  'Wetterprognose': 'Weather Forecast',
  'Wo kommen die Daten hin?': 'Where does the data go?',
  'Wärmekapazität:': 'Heat Capacity:',
  'als die EEG-Einspeisevergütung von € 0.082.': 'than the EEG feed-in tariff of € 0.082.',
  'aus dem Netz zu beziehen. Entspricht': 'to draw from the grid. Equals',
  'erzielt —': 'achieved —',
  'gekostet. Tatsächlicher Restbetrag diesen Monat:': 'cost. Actual remaining amount this month:',
  'hält thermische Energie für': 'holds thermal energy for',
  'und verdiente deinen bisher': 'and earned your so far',
  '· Bundesnetzagentur · Day-Ahead-Auktion EPEX SPOT · 15-Minuten-Auflösung · Kostenlos & offiziell': '· Federal Network Agency · Day-Ahead Auction EPEX SPOT · 15-Min. Resolution · Free & Official',
  '· Kein API-Key · Kein Proxy · Kein CORS-Problem · Direkte Browser-Anfrage': '· No API-Key · No Proxy · No CORS-Problem · Direct Browser Request',
  'ÜBERSCHREIBUNGSDAUER': 'OVERRIDE DURATION',
  '— Einspeisung zu': '— Feed-in to',
  '— eine Kombination mit KI-gesteuertem Energiemanagement, die in Deutschland noch nicht als kommerzielles Produkt erhältlich ist. Die KI entscheidet, wann Solarstrom günstiger als Wärme gespeichert wird, und wann Verkauf ins Netz sinnvoller ist.': '— a combination with AI-driven energy management not yet commercially available in Germany. The AI decides when it is cheaper to store solar power as heat and when it makes more sense to sell it to the grid.',
  '— rund 48% weniger als heute. Temperatur 18–24°C, Wind 3–6 m/s.': '— roughly 48% less than today. Temp 18-24°C, Wind 3-6 m/s.',
  '€ Einspeisung': '€ Export',
  'Aktuell': 'Current',
  'Aktuell (11°C unter Ziel)': 'Current (11°C below target)',
  'Aktuelle Temperatur': 'Current Temperature',
  'Auflösung': 'Resolution',
  'Aus Speicher versorgen': 'Supply from Storage',
  'Außentemperatur & Luftfeuchtigkeit': 'Ambient Temp & Humidity',
  'BETRIEBSMODUS WÄHLEN': 'SELECT OPERATOR MODE',
  'Batterie + Thermospeicher laden': 'Charge Battery + Thermal Store',
  'Batterie-Check — Kapazitätsmessung': 'Battery Check — Capacity Measurement',
  'Bestes Verkaufsfenster — 17:00 bis 19:00': 'Best Sales Window — 17:00 to 19:00',
  'Datenfluss-Übersicht': 'Data Flow Overview',
  'Der integrierte': 'The integrated',
  'Dieses Dashboard': 'This Dashboard',
  'Dominante KI-Entscheidung je Stunde': 'Dominant AI Decision per Hour',
  'EIGENVERSORGUNG': 'SELF-SUFFICIENCY',
  'Eigenverbrauch.': 'Self-consumption.',
  'Entsperren': 'Unlock',
  'Erstinbetriebnahme aller Systemkomponenten. MQTT-Broker, InfluxDB, Node-RED und Python KI-Controller erfolgreich deployed. Erste Testläufe mit simulierten Daten. Alle Sensoren kommunizieren korrekt.': 'Initial commissioning of all system components. MQTT broker, InfluxDB, Node-RED, and Python AI-Controller successfully deployed. First test runs with simulated data. All sensors communicating correctly.',
  'Finanzübersicht — Dieser Monat (30 Tage)': 'Financial Overview — This Month (30 Days)',
  'Geschätzte Dauer: 2h · Kosten: ~€ 80': 'Estimated Duration: 2h · Costs: ~€ 80',
  'Geschätzte Haltezeit': 'Estimated Hold Time',
  'Geschätzte Haltezeit:': 'Estimated Hold Time:',
  'Gespart durch Eigenverbrauch': 'Saved via Self-Consumption',
  'Gespeicherte Wärmeenergie': 'Stored Thermal Energy',
  'Gut isolierter Tank · entspricht ~0.28 kWh/h Verlust': 'Well insulated tank · equals ~0.28 kWh/h loss',
  'Günstig laden — 01:00 bis 04:00 Uhr': 'Cheap Charging — 01:00 to 04:00',
  'Halbjährliche Reinigung der Solarpanele geplant. Schmutz und Vogelkot können Effizienz um 5–15% reduzieren. Termin mit Dachdecker vereinbaren.': 'Biannual solar panel cleaning planned. Dirt and bird droppings can lower efficiency by 5-15%. Schedule appointment with roofer.',
  'Heizstufe (aktuell)': 'Heating Level (current)',
  'Heute produzierte dein System': 'Today your system produced',
  'Heutige Entscheidungen, neueste zuerst — mit Klartextbegründung': 'Today\\'s Decisions, newest first — with plain text reason',
  'Heutiger Solarertrag → Wärme': 'Today\\'s Solar Yield → Heat',
  'In der Nacht fallen die Spotpreise auf etwa': 'At night spot prices fall to approx',
  'Irradianzwert zeigt zwischen 14:22 und 14:35 Uhr unrealistische Spitze von 1450 Lux. Möglicherweise Reflexion durch Vogel oder Schmutzpartikel. Beobachtung fortsetzen.': 'Irradiance value shows unrealistic peak of 1450 Lux between 14:22 and 14:35. Possibly reflection by bird or dirt particles. Continue monitoring.',
  'Jahr': 'Year',
  'Jeder Sensor zeigt: aktueller Messwert · Protokoll · Datenfluss · ob Sensor aktiv speichert oder nur meldet': 'Each sensor shows: current reading · protocol · data flow · whether sensor actively stores or only reports',
  'Kapazität': 'Capacity',
  'Lade Live-Wetterdaten für Regensburg…': 'Loading Live Weather Data for Regensburg…',
  'Lade aktuelle Nachrichten von rss2json API...': 'Loading latest News from rss2json API...',
  'Letzter Service': 'Last Service',
  'MQTT Broker': 'MQTT Broker',
  'MQTT-Reconnect-Logik verbessert. DS18B20 Auslesefehler bei Temperaturen > 80°C behoben. Sampling-Rate von 30s auf 15s erhöht für bessere KI-Grundlage.': 'MQTT reconnect logic improved. DS18B20 reading error at temps > 80°C fixed. Sampling rate increased from 30s to 15s for better AI baseline.',
  'Manuell bis Abbruch': 'Manual until canceled',
  'Master-Passwort eingeben…': 'Enter Master Password…',
  'Master-Passwort erforderlich — manueller Eingriff ins KI-System': 'Master Password required — manual intervention in AI-System',
  'Minimum für Heizung': 'Minimum for Heating',
  'Modus jetzt aktivieren →': 'Activate Mode Now →',
  'Monat': 'Month',
  'Nacht · Solar nicht verfügbar · Wärmeschutz aktiv': 'Night · Solar unavailable · Heat protection active',
  'Netto-Vorteil gegenüber dem Netz.': 'Net advantage over the grid.',
  'Netzunabhängig heute': 'Off-grid today',
  'Netzunabhängigkeit — Heute': 'Grid Independence — Today',
  'Nur meldend — Umgebungsdaten fließen in Wetterkorrelation und Systemeffizienzberechnung der KI.': 'Reporting only — ambient data flows into weather correlation and system efficiency calculation of AI.',
  'Nur meldend — misst Lichtstärke (Lux) und konvertiert zu W/m². Daten fließen direkt in die KI-Entscheidung.': 'Reporting only — measures light intensity (Lux) and converts to W/m². Data flows directly into AI decision.',
  'Nächster Service': 'Next Service',
  'OTA-Update über WiFi · Downtime: 12 Sekunden · Rollback-Version gespeichert': 'OTA Update via WiFi · Downtime: 12 Seconds · Rollback Version saved',
  'Offene Warnungen': 'Open Warnings',
  'Physikalische Grundlage': 'Physical Basis',
  'Plausibilitätsprüfung aller 6 Sensoren. SCT-013 mit Referenz-Multimeter abgeglichen (+0.3% Abweichung, innerhalb Toleranz). PZEM-Zählerstand manuell verifiziert.': 'Plausibility check of all 6 sensors. SCT-013 aligned with reference multimeter (+0.3% deviation, within tolerance). PZEM meter reading manually verified.',
  'Prognostizierte Ersparnis gegenüber Tagsbezug:': 'Forecasted savings compared to daily grid draw:',
  'Prognostizierter Erlös:': 'Forecasted Revenue:',
  'Projekt-Alleinstellungsmerkmal': 'Project Unique Selling Point',
  'Python KI-Controller': 'Python AI-Controller',
  'SMARD — Strommarktdaten': 'SMARD — Electricity Market Data',
  'SPEICHERN': 'STORE',
  'STORE': 'STORE',
  'Sensor DS18B20 · GPIO 4': 'Sensor DS18B20 · GPIO 4',
  'Sensor-Dashboard — 6 aktive Sensoren · ESP32 DevKit v1': 'Sensor Dashboard — 6 active sensors · ESP32 DevKit v1',
  'Sensor: BH1750 · GPIO21/22 · I2C · Automatischer Ausreißer-Filter greift ab nächstem Zyklus': 'Sensor: BH1750 · GPIO21/22 · I2C · Automatic outlier filter active from next cycle',
  'Sicherheitsabschaltung': 'Safety Shutdown',
  'Solar (kW/kWh)': 'Solar (kW/kWh)',
  'Solarproduktion & Spotpreis — Skalierung wählen': 'Solar Prod & Spot Price — Select Scaling',
  'Solarstrom.': 'Solar power.',
  'Speicherstatus — Echtzeit': 'Storage Status — Real-time',
  'Spotpreis (€/kWh)': 'Spot Price (€/kWh)',
  'Standby': 'Standby',
  'Strom ins Netz einspeisen': 'Feed power to grid',
  'Strom ins Netz verkauft, wenn die Spotpreise hoch waren. Durchschnittlich': 'Sold power to grid when spot prices were high. Averaged',
  'Strom selbst produziert und genutzt statt für': 'Self-produced and utilized power instead of',
  'Systemanalyse': 'System Analysis',
  'Systemlaufzeit': 'System Uptime',
  'Systemstatus — 23:59 Uhr': 'System Status — 23:59',
  'Tage': 'Days',
  'Tank: 800L Pufferspeicher · Dämmstärke: 100mm PU-Schaum · TÜV-Kennzeichen vorhanden': 'Tank: 800L Buffer Storage · Insulation: 100mm PU-Foam · TÜV certified',
  'Teilweise bewölkt': 'Partly cloudy',
  'Temperatur & Solarproduktion je Stunde': 'Temperature & Solar Production per Hour',
  'Temperaturverlauf — Heute (24h)': 'Temperature Curve — Today (24h)',
  'Thermospeicher Inspektion — Wärmedämmung': 'Thermal Storage Inspection — Heat Insulation',
  'Thermospeicher — 800 Liter Pufferspeicher': 'Thermal Storage — 800 Liter Buffer Tank',
  'VERBRAUCHEN': 'CONSUME',
  'VERKAUFEN': 'SELL',
  'Visuelle Inspektion der PU-Schaum-Dämmung. Keine Feuchtigkeitsschäden sichtbar. Verlustrate 0.3°C/h entspricht Spezifikation. Sicherheitsventil getestet — einwandfrei.': 'Visual inspection of PU foam insulation. No moisture damage visible. Loss rate 0.3°C/h meets specification. Safety valve tested — flawless.',
  'Vollzyklus-Test: 100% → 10% → 100%. Nutzbare Kapazität: 12.3 kWh (Nennwert 12.5 kWh, 98.4%). Alle 16 Zellen innerhalb 20mV Spannungstoleranz. Keine Degradation festgestellt.': 'Full cycle test: 100% -> 10% -> 100%. Usable capacity: 12.3 kWh (Nominal 12.5 kWh, 98.4%). All 16 cells within 20mV voltage tolerance. No degradation detected.',
  'Wartungsprotokoll — Systemereignisse & geplante Maßnahmen': 'Maintenance Log — System Events & Planned Measures',
  'Was du ohne SolarAI bezahlt hättest': 'What you would have paid without SolarAI',
  'Admin-Override öffnen': 'Open Admin-Override',
  'Aktuell': 'Current',
  'Jan': 'Jan', 'Feb': 'Feb', 'Mär': 'Mar', 'Apr': 'Apr', 'Mai': 'May', 'Jun': 'Jun', 'Jul': 'Jul', 'Aug': 'Aug', 'Sep': 'Sep', 'Okt': 'Oct', 'Nov': 'Nov', 'Dez': 'Dec',
  'Zyklen gesamt': 'Total Cycles',
  'Spannung': 'Voltage',
  'Leistung': 'Power',
  'Typ': 'Type',
  'Genauigkeit': 'Accuracy',
  'Abtastrate': 'Sampling Rate',
  'Datenfluss': 'Data Flow',
  'Umrechnung': 'Conversion',
  'Bereich': 'Range',
  'Luftfeuchtigkeit': 'Humidity',
  'Messintervall': 'Meas Interval'
};\n'''

content = content[:start_idx] + NEW_DICT + content[end_idx:]

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print('Success')
